<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Faker\Factory as Faker;

class PeluqueriasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create('es_ES');

        DB::table('peluquerias')->insert([
            [
                'nombre' => 'Peluquería Rosa',
                'descripcion' => 'Peluquería unisex con amplia experiencia. Cortes clásicos y modernos, coloración y tratamientos capilares.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'rosa@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'UNISEX',
                'contrasenia' => Hash::make('password123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Barber Shop El Barbero',
                'descripcion' => 'Barbería especializada en cortes masculinos. Afeitados clásicos, arreglo de barba y cortes de tendencia.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'barber@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'BARBERIA',
                'contrasenia' => Hash::make('secreto456'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Peluquería Carmen',
                'descripcion' => 'Peluquería para señoras. Peinados, recogidos para eventos y tratamientos de belleza.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'carmen@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'PELUQUERIA',
                'contrasenia' => Hash::make('carmen123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Peluquería María',
                'descripcion' => 'Especialistas en coloración y mechas. Las últimas tendencias en color y cuidado del cabello.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'maria@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'PELUQUERIA',
                'contrasenia' => Hash::make('maria123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'nombre' => 'Barbería Jose',
                'descripcion' => 'Barbería clásica con un toque moderno. Cortes de pelo, arreglo de barba y afeitados tradicionales.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'jose@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'BARBERIA',
                'contrasenia' => Hash::make('jose123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Salón de Belleza Ana',
                'descripcion' => 'Salón de belleza con servicios de peluquería, estética y maquillaje.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'ana@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'UNISEX',
                'contrasenia' => Hash::make('ana123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Estilistas Laura',
                'descripcion' => 'Peluquería de autor. Estilos personalizados y asesoramiento de imagen.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'laura@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'PELUQUERIA',
                'contrasenia' => Hash::make('laura123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Barbería Los Hermanos',
                'descripcion' => 'Barbería tradicional con un ambiente familiar. Cortes de pelo y arreglo de barba.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'hermanos@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'BARBERIA',
                'contrasenia' => Hash::make('hermanos123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Peluquería Moderna',
                'descripcion' => 'Peluquería con las últimas tendencias en cortes, coloración y peinados.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'moderna@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'UNISEX',
                'contrasenia' => Hash::make('moderna123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'El Rincón del Barbero',
                'descripcion' => 'Barbería especializada en afeitados clásicos con toalla caliente.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'rincon@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'BARBERIA',
                'contrasenia' => Hash::make('rincon123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'nombre' => 'Peluquería Estilo',
                'descripcion' => 'Peluquería unisex con un ambiente moderno y acogedor.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'estilo@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'UNISEX',
                'contrasenia' => Hash::make('estilo123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Barbería Clásica',
                'descripcion' => 'Barbería tradicional con el encanto de antaño. Cortes y afeitados clásicos.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'clasica@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'BARBERIA',
                'contrasenia' => Hash::make('clasica123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Peluquería Infantil',
                'descripcion' => 'Peluquería especializada en cortes de pelo para niños y niñas. Ambiente divertido y personal amable.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'infantil@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'PELUQUERIA',
                'contrasenia' => Hash::make('infantil123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Barbería Urbana',
                'descripcion' => 'Barbería con un estilo urbano y moderno. Cortes de pelo y arreglo de barba de tendencia.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'urbana@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'BARBERIA',
                'contrasenia' => Hash::make('urbana123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Peluquería Familiar',
                'descripcion' => 'Peluquería para toda la familia. Cortes de pelo, coloración y tratamientos capilares.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'familiar@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'UNISEX',
                'contrasenia' => Hash::make('familiar123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Barbería Vintage',
                'descripcion' => 'Barbería con decoración vintage y ambiente retro. Cortes y afeitados clásicos.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'vintage@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'BARBERIA',
                'contrasenia' => Hash::make('vintage123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Peluquería Creativa',
                'descripcion' => 'Peluquería especializada en estilos creativos y vanguardistas. Cortes de pelo y coloración originales.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'creativa@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'PELUQUERIA',
                'contrasenia' => Hash::make('creativa123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Barbería de Autor',
                'descripcion' => 'Barbería con un estilo único y personal. Cortes de pelo y arreglo de barba personalizados.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'autor@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'BARBERIA',
                'contrasenia' => Hash::make('autor123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Peluquería y Estética',
                'descripcion' => 'Centro de belleza que ofrece servicios de peluquería, estética y tratamientos de belleza. Ambiente moderno y profesional, con servicios personalizados.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'estetica@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'UNISEX',
                'contrasenia' => Hash::make('estetica123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Barbería Premium',
                'descripcion' => 'Barbería de lujo con servicios exclusivos. Cortes de pelo, afeitados y tratamientos de alta gama.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 5),
                'email' => 'premium@example.com',
                'telefono' => $faker->phoneNumber,
                'tipo' => 'BARBERIA',
                'contrasenia' => Hash::make('premium123'),
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
