<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Faker\Factory as Faker;

class PeluqueriasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create('es_ES');

        DB::table('peluquerias')->insert([
            [
                'id' => 1,
                'nombre' => 'Salón de Belleza Ana',
                'descripcion' => 'Salón de belleza con servicios de peluquería, estética y maquillaje.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'ana@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'UNISEX',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => 1,
            ],
            [
                'id' => 2,
                'nombre' => 'Peluquería Rosa',
                'descripcion' => 'Peluquería unisex con amplia experiencia. Cortes clásicos y modernos, coloración y tratamientos capilares.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'rosa@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'UNISEX',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => 2,
            ],
            [
                'id' => 3,
                'nombre' => 'Barber Shop El Barbero',
                'descripcion' => 'Barbería especializada en cortes masculinos. Afeitados clásicos, arreglo de barba y cortes de tendencia.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'barber@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'BARBERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 4,
                'nombre' => 'Peluquería Carmen',
                'descripcion' => 'Peluquería para señoras. Peinados, recogidos para eventos y tratamientos de belleza.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'carmen@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'PELUQUERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 5,
                'nombre' => 'Peluquería María',
                'descripcion' => 'Especialistas en coloración y mechas. Las últimas tendencias en color y cuidado del cabello.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'maria@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'PELUQUERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 6,
                'nombre' => 'Barbería Jose',
                'descripcion' => 'Barbería clásica con un toque moderno. Cortes de pelo, arreglo de barba y afeitados tradicionales.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'jose@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'BARBERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 7,
                'nombre' => 'Estilistas Laura',
                'descripcion' => 'Peluquería de autor. Estilos personalizados y asesoramiento de imagen.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'laura@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'PELUQUERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 8,
                'nombre' => 'Barbería Los Hermanos',
                'descripcion' => 'Barbería tradicional con un ambiente familiar. Cortes de pelo y arreglo de barba.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'hermanos@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'BARBERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 9,
                'nombre' => 'Peluquería Moderna',
                'descripcion' => 'Peluquería con las últimas tendencias en cortes, coloración y peinados.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'moderna@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'UNISEX',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 10,
                'nombre' => 'El Rincón del Barbero',
                'descripcion' => 'Barbería especializada en afeitados clásicos con toalla caliente.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'rincon@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'BARBERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 11,
                'nombre' => 'Peluquería Estilo',
                'descripcion' => 'Peluquería unisex con un ambiente moderno y acogedor.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'estilo@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'UNISEX',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 12,
                'nombre' => 'Barbería Clásica',
                'descripcion' => 'Barbería tradicional con el encanto de antaño. Cortes y afeitados clásicos.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'clasica@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'BARBERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 13,
                'nombre' => 'Peluquería Infantil',
                'descripcion' => 'Peluquería especializada en cortes de pelo para niños y niñas. Ambiente divertido y personal amable.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'infantil@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'PELUQUERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 14,
                'nombre' => 'Barbería Urbana',
                'descripcion' => 'Barbería con un estilo urbano y moderno. Cortes de pelo y arreglo de barba de tendencia.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'urbana@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'BARBERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 15,
                'nombre' => 'Peluquería Familiar',
                'descripcion' => 'Peluquería para toda la familia. Cortes de pelo, coloración y tratamientos capilares.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'familiar@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'UNISEX',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 16,
                'nombre' => 'Barbería Vintage',
                'descripcion' => 'Barbería con decoración vintage y ambiente retro. Cortes y afeitados clásicos.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'vintage@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'BARBERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 17,
                'nombre' => 'Peluquería Creativa',
                'descripcion' => 'Peluquería especializada en estilos creativos y vanguardistas. Cortes de pelo y coloración originales.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'creativa@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'PELUQUERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 18,
                'nombre' => 'Barbería de Autor',
                'descripcion' => 'Barbería con un estilo único y personal. Cortes de pelo y arreglo de barba personalizados.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'autor@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'BARBERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 19,
                'nombre' => 'Peluquería y Estética',
                'descripcion' => 'Centro de belleza que ofrece servicios de peluquería, estética y tratamientos de belleza. Ambiente moderno y profesional, con servicios personalizados.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'estetica@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'UNISEX',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
            [
                'id' => 20,
                'nombre' => 'Barbería Premium',
                'descripcion' => 'Barbería de lujo con servicios exclusivos. Cortes de pelo, afeitados y tratamientos de alta gama.',
                'direccion' => $faker->streetAddress,
                'localidad' => $faker->numberBetween(1, 7),
                'email' => 'premium@gmail.com',
                'telefono' => $faker->regexify('[6-9]{1}[0-9]{8}'),
                'tipo' => 'BARBERIA',
                'valoracion' => $faker->randomFloat(1, 1, 5),
                'created_at' => now(),
                'updated_at' => now(),
                'user_id' => null,
            ],
        ]);
    }
}
