<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiciosPeluqueriaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('servicios_peluqueria')->insert([
            ['id_peluqueria' => 1, 'id_servicio' => 1, 'precio' => 15.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 1, 'id_servicio' => 2, 'precio' => 25.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 1, 'id_servicio' => 11, 'precio' => 20.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 1, 'id_servicio' => 12, 'precio' => 35.0, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 1, 'id_servicio' => 15, 'precio' => 25.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 1, 'id_servicio' => 21, 'precio' => 10.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 1, 'id_servicio' => 23, 'precio' => 12.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 2, 'id_servicio' => 1, 'precio' => 12.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 2, 'id_servicio' => 2, 'precio' => 20.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 2, 'id_servicio' => 4, 'precio' => 15.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 2, 'id_servicio' => 9, 'precio' => 18.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 2, 'id_servicio' => 21, 'precio' => 8.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 3, 'id_servicio' => 11, 'precio' => 18.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 3, 'id_servicio' => 12, 'precio' => 40.0, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 3, 'id_servicio' => 16, 'precio' => 30.0, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 3, 'id_servicio' => 15, 'precio' => 22.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 3, 'id_servicio' => 21, 'precio' => 12.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 4, 'id_servicio' => 12, 'precio' => 38.0, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 4, 'id_servicio' => 14, 'precio' => 50.0, 'duracion' => 90, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 4, 'id_servicio' => 15, 'precio' => 25.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 4, 'id_servicio' => 18, 'precio' => 60.0, 'duracion' => 120, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 4, 'id_servicio' => 21, 'precio' => 10.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 5, 'id_servicio' => 1, 'precio' => 14.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 5, 'id_servicio' => 4, 'precio' => 16.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 5, 'id_servicio' => 9, 'precio' => 20.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 5, 'id_servicio' => 21, 'precio' => 9.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 5, 'id_servicio' => 23, 'precio' => 10.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 6, 'id_servicio' => 1, 'precio' => 16.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 6, 'id_servicio' => 11, 'precio' => 22.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 6, 'id_servicio' => 12, 'precio' => 40.0, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 6, 'id_servicio' => 15, 'precio' => 28.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 6, 'id_servicio' => 21, 'precio' => 12.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 6, 'id_servicio' => 23, 'precio' => 14.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 7, 'id_servicio' => 11, 'precio' => 20.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 7, 'id_servicio' => 12, 'precio' => 42.0, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 7, 'id_servicio' => 14, 'precio' => 55.0, 'duracion' => 90, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 7, 'id_servicio' => 16, 'precio' => 35.0, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 7, 'id_servicio' => 21, 'precio' => 11.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 8, 'id_servicio' => 1, 'precio' => 13.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 8, 'id_servicio' => 2, 'precio' => 22.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 8, 'id_servicio' => 4, 'precio' => 14.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 8, 'id_servicio' => 9, 'precio' => 19.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 8, 'id_servicio' => 21, 'precio' => 8.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 9, 'id_servicio' => 1, 'precio' => 15.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 9, 'id_servicio' => 11, 'precio' => 20.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 9, 'id_servicio' => 12, 'precio' => 38.0, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 9, 'id_servicio' => 15, 'precio' => 25.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 9, 'id_servicio' => 21, 'precio' => 10.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 9, 'id_servicio' => 23, 'precio' => 12.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 10, 'id_servicio' => 1, 'precio' => 14.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 10, 'id_servicio' => 4, 'precio' => 18.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 10, 'id_servicio' => 9, 'precio' => 20.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 10, 'id_servicio' => 21, 'precio' => 9.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 10, 'id_servicio' => 23, 'precio' => 11.0, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 11, 'id_servicio' => 14, 'precio' => 55.28, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 11, 'id_servicio' => 2, 'precio' => 24.96, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 11, 'id_servicio' => 1, 'precio' => 12.39, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 11, 'id_servicio' => 15, 'precio' => 24.41, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 11, 'id_servicio' => 12, 'precio' => 33.35, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 11, 'id_servicio' => 18, 'precio' => 54.94, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 11, 'id_servicio' => 23, 'precio' => 11.82, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 11, 'id_servicio' => 16, 'precio' => 27.88, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 12, 'id_servicio' => 12, 'precio' => 42.43, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 12, 'id_servicio' => 14, 'precio' => 44.73, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 12, 'id_servicio' => 9, 'precio' => 21.02, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 12, 'id_servicio' => 23, 'precio' => 12.5, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 12, 'id_servicio' => 18, 'precio' => 57.12, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 12, 'id_servicio' => 4, 'precio' => 14.12, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 12, 'id_servicio' => 15, 'precio' => 28.43, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 12, 'id_servicio' => 11, 'precio' => 19.02, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 13, 'id_servicio' => 2, 'precio' => 23.87, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 13, 'id_servicio' => 23, 'precio' => 11.93, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 13, 'id_servicio' => 18, 'precio' => 68.52, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 13, 'id_servicio' => 21, 'precio' => 9.54, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 13, 'id_servicio' => 9, 'precio' => 19.55, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 13, 'id_servicio' => 15, 'precio' => 27.47, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 13, 'id_servicio' => 11, 'precio' => 20.71, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 13, 'id_servicio' => 1, 'precio' => 15.67, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 14, 'id_servicio' => 16, 'precio' => 35.96, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 14, 'id_servicio' => 12, 'precio' => 43.1, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 14, 'id_servicio' => 2, 'precio' => 21.53, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 14, 'id_servicio' => 1, 'precio' => 13.94, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 14, 'id_servicio' => 14, 'precio' => 57.76, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 14, 'id_servicio' => 23, 'precio' => 10.61, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 14, 'id_servicio' => 11, 'precio' => 19.13, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 14, 'id_servicio' => 9, 'precio' => 20.23, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 15, 'id_servicio' => 18, 'precio' => 55.86, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 15, 'id_servicio' => 14, 'precio' => 59.2, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 15, 'id_servicio' => 2, 'precio' => 23.59, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 15, 'id_servicio' => 11, 'precio' => 18.32, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 15, 'id_servicio' => 12, 'precio' => 36.78, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 15, 'id_servicio' => 16, 'precio' => 35.12, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 15, 'id_servicio' => 4, 'precio' => 13.65, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 15, 'id_servicio' => 21, 'precio' => 10.86, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 16, 'id_servicio' => 21, 'precio' => 9.05, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 16, 'id_servicio' => 23, 'precio' => 11.8, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 16, 'id_servicio' => 15, 'precio' => 27.89, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 16, 'id_servicio' => 2, 'precio' => 23.29, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 16, 'id_servicio' => 12, 'precio' => 34.67, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 16, 'id_servicio' => 16, 'precio' => 28.99, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 16, 'id_servicio' => 18, 'precio' => 64.41, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 16, 'id_servicio' => 11, 'precio' => 20.23, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 17, 'id_servicio' => 18, 'precio' => 59.88, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 17, 'id_servicio' => 16, 'precio' => 34.99, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 17, 'id_servicio' => 23, 'precio' => 13.08, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 17, 'id_servicio' => 14, 'precio' => 47.03, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 17, 'id_servicio' => 21, 'precio' => 8.89, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 17, 'id_servicio' => 2, 'precio' => 23.54, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 17, 'id_servicio' => 9, 'precio' => 19.81, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 17, 'id_servicio' => 15, 'precio' => 24.14, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 18, 'id_servicio' => 16, 'precio' => 34.27, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 18, 'id_servicio' => 4, 'precio' => 15.92, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 18, 'id_servicio' => 9, 'precio' => 17.9, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 18, 'id_servicio' => 15, 'precio' => 26.06, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 18, 'id_servicio' => 1, 'precio' => 12.49, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 18, 'id_servicio' => 21, 'precio' => 9.71, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 18, 'id_servicio' => 23, 'precio' => 11.64, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 18, 'id_servicio' => 14, 'precio' => 59.65, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 19, 'id_servicio' => 18, 'precio' => 66.15, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 19, 'id_servicio' => 15, 'precio' => 25.06, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 19, 'id_servicio' => 9, 'precio' => 17.51, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 19, 'id_servicio' => 11, 'precio' => 19.24, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 19, 'id_servicio' => 2, 'precio' => 20.06, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 19, 'id_servicio' => 23, 'precio' => 13.41, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 19, 'id_servicio' => 21, 'precio' => 11.15, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 19, 'id_servicio' => 16, 'precio' => 36.58, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 20, 'id_servicio' => 16, 'precio' => 28.19, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 20, 'id_servicio' => 21, 'precio' => 11.02, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 20, 'id_servicio' => 4, 'precio' => 17.86, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 20, 'id_servicio' => 1, 'precio' => 12.38, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 20, 'id_servicio' => 2, 'precio' => 22.24, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 20, 'id_servicio' => 11, 'precio' => 17.42, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 20, 'id_servicio' => 23, 'precio' => 12.72, 'duracion' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['id_peluqueria' => 20, 'id_servicio' => 18, 'precio' => 64.79, 'duracion' => 60, 'created_at' => now(), 'updated_at' => now()]
        ]);
    }
}